[package]
name = "rust-shell"
version = "0.1.0"
authors = ["Strife01"]
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow = "1.0.68"
bytes = "1.3.0"
thiserror = "1.0.38"
rustyline = "15.0.0"
walkdir = "2.5.0"
